# Generated by Django 4.2.13 on 2026-05-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
