# Generated by Django 4.2.13 on 2026-05-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('target_model', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activities__created_b33631_idx'), models.Index(fields=['user'], name='activities__user_id_a9ae64_idx'), models.Index(fields=['target_model'], name='activities__target__bd862e_idx')],
            },
        ),
    ]
